add pyssg.xyz configs and templates

diff --git a/pyssg.xyz/bs b/pyssg.xyz/bs
--- a/pyssg.xyz/bs
+++ b/pyssg.xyz/bs
@@ -5,5 +5,10 @@ PYSSG_XYZ_DIR=$HOME/pyssg/pyssg.xyz
 
 pyssg --config $PYSSG_XYZ_DIR/config.yaml -b --debug
 
+if [ $? -ne 0 ]; then
+echo "Failed to build the site."
+exit 1
+fi
+
 echo "rsync: pushing (U) local (pyssg.xyz) to webserver (luevano.xyz). (pyssg.xyz)"
 rsync -rtuvPL --delete-after --exclude-from=$PYSSG_XYZ_DIR/.rsyncignore $PYSSG_XYZ_DIR/live/ luevanor:/var/www/pyssg.xyz/
